development: &default
  adapter: postgresql
  database: camp_colorado_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: camp_colorado_test
